# https://github.com/jderusse/docker-gitsplit
cache_url: "cache/gitsplit"
splits:
  - prefix: "src/LaravelCache"
    target: "https://${GH_TOKEN}@github.com/webman-tech/laravel-cache.git"
  - prefix: "src/LaravelConsole"
    target: "https://${GH_TOKEN}@github.com/webman-tech/laravel-console.git"
  - prefix: "src/LaravelDatabase"
    target: "https://${GH_TOKEN}@github.com/webman-tech/laravel-database.git"
  - prefix: "src/LaravelFilesystem"
    target: "https://${GH_TOKEN}@github.com/webman-tech/laravel-filesystem.git"
  - prefix: "src/LaravelHttp"
    target: "https://${GH_TOKEN}@github.com/webman-tech/laravel-http.git"
  - prefix: "src/LaravelRedis"
    target: "https://${GH_TOKEN}@github.com/webman-tech/laravel-redis.git"
  - prefix: "src/LaravelTranslation"
    target: "https://${GH_TOKEN}@github.com/webman-tech/laravel-translation.git"
  - prefix: "src/LaravelValidation"
    target: "https://${GH_TOKEN}@github.com/webman-tech/laravel-validation.git"
origins:
  - ^\d+.x$
  - ^v\d+\.\d+\.\d+$
