name: gitsplit
on:
  push:
    branches:
      - '*.x'
  release:
    types: [published]

jobs:
  gitsplit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        run: git clone https://github.com/webman-tech/laravel-monorepo /home/runner/work/webman-tech/laravel-monorepo && cd /home/runner/work/webman-tech/laravel-monorepo
      - name: Split repositories
        uses: docker://jderusse/gitsplit:latest
        with:
          args: gitsplit
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
